version: '3.9'
services:
  db:
    image: 'postgres:13.2-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
    ports:
      - 5003:5432
