version: '3.9'
services:
  web:
    build:
      context: .
      target: web
    volumes:
      - ./:/app
    ports:
      - '5001:5001'

  server:
    build:
      context: .
      target: server
    volumes:
      - ./:/app
    ports:
      - '5002:5002'
