version: '3.9'
services:
  web:
    build:
      context: .
      target: web
    volumes:
      - ./:/app
    ports:
      - '5001:5001'
    depends_on:
      - server

  server:
    build:
      context: .
      target: server
    volumes:
      - ./:/app
    ports:
      - '5002:5002'
    depends_on:
      - db

  db:
    image: 'postgres:13.2-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
